---
- name: Base Machine Configuration
  hosts: all
  sudo: yes
  tasks:
  - name: Install epel-release
    yum: name=epel-release state=latest update_cache=yes

  - name: Install dependencies
    yum: name={{ item }} state=latest
    with_items:
    - libselinux-python
    - python-setuptools
    - openssl
    - numactl

  - name: Fix /etc/hosts
    lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line='127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4' owner=root group=root mode=0644

  - name: Install httplib2
    easy_install: name=httplib2

  - name: Disable iptables
    service: name=iptables state=stopped enabled=no

  - name: Disable SELinux
    selinux: state=disabled

  - name: Turn down swapiness
    sysctl: name=vm.swappiness value=0 state=present
    ignore_errors: true

  - name: Disable THP
    shell: "{{ item }}" 
    with_items:
    - echo 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' >> /etc/rc.local
    - echo 'echo never > /sys/kernel/mm/transparent_hugepage/defrag' >> /etc/rc.local
    - echo never > /sys/kernel/mm/transparent_hugepage/enabled
    - echo never > /sys/kernel/mm/transparent_hugepage/defrag

  - name: Increase open files
    shell: echo "* - nofile 65536" >> /etc/security/limits.conf

  - name: Disable NUMA
    sysctl: name=vm.zone_reclaim_mode value=0 state=present
    ignore_errors: true

  - name: Check if deps exists
    stat: path=/vagrant/deps
    register: deps

  - name: Create deps Directory
    file: path=/vagrant/deps state=directory
    when: deps.stat.exists == False
